### ISSUE TITLE
Домашнее задание по промисам

### ISSUE THREAD

**Issue by tiny-kottan** [Yevs/kottans-homework#7]
Написать `Promise.map`, `Promise.some` и `Promise.reduce`. Должно работать как в доках блуберда: http://bluebirdjs.com/docs/api-reference.html. Тесты: https://github.com/petkaantonov/bluebird/tree/master/test/mocha
Промис нужно сабклассить. `Promise.all` не юзать. Брать конструктор промиса из this

**Comment by Yevs** [comment]
https://github.com/Yevs/kottans-homework/tree/master/week04
