### ISSUE TITLE
Домашнее задание по тестированию

### ISSUE THREAD

**Issue by tiny-kottan** [Yevs/kottans-homework#8]
https://github.com/timoxley/functional-javascript-workshop - complete 'Function Spies' exercise.
Investigate following questions:
  1) What are stubs, mocks? What is the difference?
  2) What is the difference between TDD and BDD?
Read about several test frameworks / setups, pick one (qunit, jasmine, mocha, ava, tape). 
Do Kata #1 using it.

**Comment by Yevs** [comment]
https://github.com/Yevs/kottans-homework/tree/master/week06
